import type { ProductVariant } from "./domain";

export const mockVariants: ProductVariant[] = [
  {
    id: "var-001",
    productName: "Bota Cuadra piel de venado",
    brand: "Cuadra",
    legacyCode: "750104020251",
    color: "Café",
    size: "25",
    price: 4890,
    stock: 3,
    image: "/products/bota.webp",
  },
  {
    id: "var-002",
    productName: "Bota Cuadra piel de venado",
    brand: "Cuadra",
    legacyCode: "750104020268",
    color: "Café",
    size: "26",
    price: 4890,
    stock: 1,
    image: "/products/bota.webp",
  },
  {
    id: "var-003",
    productName: "Sombrero 100X El Patrón",
    brand: "Tombstone",
    legacyCode: "750204310570",
    color: "Arena",
    size: "57",
    price: 2890,
    stock: 5,
    image: "/products/sombrero.webp",
  },
  {
    id: "var-004",
    productName: "Cinturón vaquero bordado",
    brand: "Vaquero SM",
    legacyCode: "000078421034",
    color: "Miel",
    size: "34",
    price: 890,
    stock: 8,
    image: "/products/cinturon.webp",
  },
  {
    id: "var-005",
    productName: "Camisa western manga larga",
    brand: "Ariat",
    legacyCode: "195696170455",
    color: "Azul",
    size: "M",
    price: 1690,
    stock: 0,
    image: "/products/camisa.webp",
  },
];
